services:
  db:
    container_name: grupo3_db
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: pf$$6#iAEQ#@y7vMnXiTXLLC#wiEHcn
      MYSQL_DATABASE: test
      MYSQL_USER: manager_test
      MYSQL_PASSWORD: RqoKdtp88Z94v7vL#XKVHPxWdb9dw
    volumes:
      - ./Base de datos/test.sql:/docker-entrypoint-initdb.d/init.sql
      - data:/var/lib/mysql
    networks:
      - red_taller_software

  backend:
    container_name: grupo3_backend
    build:
      context: .
      dockerfile: ./Backend/Dockerfile
    depends_on:
      - db
    networks:
      - red_taller_software
    environment:
      - PORT=4003
      - ORIGIN=http://grupo3.146.83.216.166.nip.io
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=manager_test
      - DB_PASSWORD=RqoKdtp88Z94v7vL#XKVHPxWdb9dw
      - DB_NAME=test

  frontend:
    container_name: grupo3_frontend
    build:
      context: ./Frontend
      dockerfile: ./dockerfile
    networks:
      - red_taller_software
    env_file:
      - ./Frontend/.env

volumes:
  data:
    external: false

networks:
  red_taller_software:
    external: true